import math
import random
from datetime import datetime

class AdvancedFeatures:
    def __init__(self):
        # 2026 Spot Prices & Tactical Baselines
        self.market_baselines = {
            "NIFTY_50": 26850.00,
            "KSE_100": 74200.00,
            "BRENT_CRUDE": 94.20,
            "GOLD_10G": 78400.00,
            "USD_INR": 84.45,
            "EU_NAT_GAS": 48.20,
            "WHEAT_FUTURES": 710.00,
            "SEMICON_INDEX": 4200.00
        }

    def _sanitize_zone(self, zone):
        """Cleans theater names for high-speed logic matching."""
        if not zone: return "GLOBAL"
        return zone.split(' ')[0].split('-')[0].upper()

    # --- 1. MULTI-DOMAIN THREAT MATRIX ---
    def generate_threat_matrix(self, gpti_score, conflict_zone):
        """Calculates 5-axis threat levels using a weighted intensity formula."""
        zone = self._sanitize_zone(conflict_zone)
        base = gpti_score * 100
        
        matrix = {
            "Kinetic (Military)": min(100, base * 1.05),
            "Narrative (PsyOps)": min(100, base * 1.15),
            "Economic Linkage": min(100, base * 0.85),
            "Cyber & Grid": min(100, base * 1.10),
            "Nuclear Posture": min(100, base * 0.70 if gpti_score < 0.8 else base * 1.3)
        }

        # Theater Overrides
        if zone == "RUSSIA" or zone == "UKRAINE":
            matrix["Economic Linkage"] += 15
            matrix["Cyber & Grid"] += 10
        elif zone == "INDIA" or zone == "PAKISTAN":
            matrix["Narrative (PsyOps)"] += 20
        elif zone == "IRAN" or zone == "ISRAEL":
            matrix["Cyber & Grid"] += 25
            matrix["Nuclear Posture"] += 15

        return {k: round(min(100, v), 2) for k, v in matrix.items()}

    # --- 2. THE BUTTERFLY EFFECT: ECONOMIC FALLOUT ---
    def get_economic_impact(self, gpti_score, conflict_zone):
        """Maps local tension to global market shocks using exponential scaling."""
        zone = self._sanitize_zone(conflict_zone)
        impact = {}
        # Intensity Factor based on Euler's Constant
        intensity = (math.exp(gpti_score) - 1) / (math.e - 1) 
        
        if zone in ["INDIA", "PAKISTAN"]:
            n_drop = self.market_baselines["NIFTY_50"] * (1 - (intensity * 0.08))
            impact["Indicator_1"] = {"name": "NIFTY 50", "value": n_drop, "delta": -(intensity * 8), "symbol": "₹"}
            k_drop = self.market_baselines["KSE_100"] * (1 - (intensity * 0.15))
            impact["Indicator_2"] = {"name": "KSE-100", "value": k_drop, "delta": -(intensity * 15), "symbol": "₨"}
            u_spike = self.market_baselines["USD_INR"] * (1 + (intensity * 0.04))
            impact["Indicator_3"] = {"name": "USD/INR", "value": u_spike, "delta": (intensity * 4), "symbol": "₹"}

        elif zone in ["RUSSIA", "UKRAINE", "EU"]:
            gas = self.market_baselines["EU_NAT_GAS"] * (1 + (intensity * 2.5))
            impact["Indicator_1"] = {"name": "EU Natural Gas", "value": gas, "delta": (intensity * 250), "symbol": "€"}
            wheat = self.market_baselines["WHEAT_FUTURES"] * (1 + (intensity * 1.8))
            impact["Indicator_2"] = {"name": "Wheat Futures", "value": wheat, "delta": (intensity * 180), "symbol": "$"}
            brent = self.market_baselines["BRENT_CRUDE"] * (1 + (intensity * 1.2))
            impact["Indicator_3"] = {"name": "Brent Crude Oil", "value": brent, "delta": (intensity * 120), "symbol": "$"}

        else: # Global/Middle East
            brent = self.market_baselines["BRENT_CRUDE"] * (1 + (intensity * 2.0))
            impact["Indicator_1"] = {"name": "Brent Crude Oil", "value": brent, "delta": (intensity * 200), "symbol": "$"}
            chips = self.market_baselines["SEMICON_INDEX"] * (1 - (intensity * 1.5))
            impact["Indicator_2"] = {"name": "SOX Chip Index", "value": chips, "delta": -(intensity * 150), "symbol": "$"}
            gold = self.market_baselines["GOLD_10G"] * (1 + (intensity * 1.1))
            impact["Indicator_3"] = {"name": "Gold (Hedge)", "value": gold, "delta": (intensity * 110), "symbol": "₹"}

        return impact

    # --- 3. AI PSYOP & INTEGRITY AUDIT (FIXED & ADDED) ---
    def analyze_information_integrity(self, headline, sitrep):
        """Detects sophisticated 2026 propaganda markers."""
        text = (str(headline) + " " + str(sitrep)).lower()
        score = 100
        flags = []

        psyop_markers = {
            "Bot Swarm": ["retweet", "viral", "trending", "unverified footage", "everyone must see"],
            "State Narrative": ["glorious", "liberation", "puppet", "unprovoked attack", "total destruction"],
            "AI Synthesis": ["deepfake", "ai-generated", "synthetic", "generated by ai", "video evidence shows"],
            "Economic Warfare": ["sanctions fail", "currency collapse", "bank run imminent"]
        }

        for category, keywords in psyop_markers.items():
            matches = [k for k in keywords if k in text]
            if matches:
                deduction = 20 if category != "AI Synthesis" else 35
                score -= deduction
                flags.append(f"{category}")

        status = "Verified Organic" if score >= 85 else ("Disputed" if score >= 60 else "High-Intensity PsyOp")
        return {"integrity_score": max(0, score), "narrative_status": status, "flags": flags}

    # --- 4. TACTICAL LEADING INDICATORS (CONSOLIDATED) ---
    def analyze_leading_indicators(self, headline, conflict_zone):
        """Checks for 'First Strike' indicators in OSINT feed."""
        text = headline.lower()
        zone = self._sanitize_zone(conflict_zone)
        
        triggers = {
            "Airspace/NOTAM": ["notam", "airspace", "no-fly", "flight cancellation", "aviation alert"],
            "Satellite Recon": ["satellite imagery", "reconnaissance", "imagery confirms", "orbital view", "drone"],
            "Electronic Warfare": ["gps jamming", "comms blackout", "ddos", "cyberattack", "grid failure", "intercept"],
            "Mobilization": ["troop movement", "artillery", "armor column", "convoys", "reserve call-up", "loc firing", "border"]
        }

        results = {name: any(kw in text for kw in kws) for name, kws in triggers.items()}
        
        # Theater-specific auto-triggers
        if zone == "INDIA" and ("loc" in text or "firing" in text or "kashmir" in text):
            results["Mobilization"] = True
            
        return results

    # --- 5. SOCIAL PANIC CALCULATOR ---
    def get_public_panic_index(self, gpti_score):
        """Determines the 'Civilian Fear Index' based on Sigmoid curve logic."""
        # P(g) = 100 / (1 + e^-10(g - 0.6))
        k = 10 
        x0 = 0.6 
        panic = 100 / (1 + math.exp(-k * (gpti_score - x0)))
        
        terms_pool = ["Emergency Kit", "Nearest Bunker", "Flight Status", "Bank Withdrawal", "Fuel Prices", "Draft Age"]
        trending = random.sample(terms_pool, 2) if gpti_score > 0.4 else ["Market Stability", "Weather Update"]
        
        return round(panic, 2), trending

    # --- 6. EARLY WARNING ALERTS ---
    def generate_alerts(self, current_gpti, gpti_trend):
        """Generates technical alerts based on GPTI levels and acceleration."""
        alerts = []
        if current_gpti >= 0.80:
            alerts.append("🔴 CRITICAL: Kinetic Engagement Imminent. DEFCON 1 logic active.")
        elif current_gpti >= 0.65:
            alerts.append("🟠 WARNING: Major Mobilization detected. GPTI violation.")
            
        if gpti_trend > 0.15:
            alerts.append("⚠️ MOMENTUM ALERT: Rapid escalation detected in current cycle.")
            
        status = "Accelerating" if gpti_trend > 0.08 else "Stable" if abs(gpti_trend) <= 0.08 else "De-escalating"
        return alerts, status