import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import pydeck as pdk
from plotly.subplots import make_subplots
import index_calculator
import data_ingestion
import analysis_engine
import config
import json
import os
from datetime import datetime
import time

# Add this near the top of your app
# This tells Streamlit to rerun the script every 60 seconds
from streamlit_autorefresh import st_autorefresh

# ... inside your main code ...
# Run this right at the start
count = st_autorefresh(interval=60 * 1000, key="data_refresh")
# ==========================================
# 1. PAGE CONFIGURATION & STYLING
# ==========================================
st.set_page_config(
    layout="wide", 
    page_title="GeoSentinel Commander",
    page_icon="🛡️",
    initial_sidebar_state="expanded"
)

# Custom CSS for "Military-Grade" Aesthetic
st.markdown("""
<style>
    .main .block-container { padding-top: 1rem; padding-bottom: 3rem; }
    h1, h2, h3 { color: #E63946; font-family: 'Helvetica Neue', sans-serif; font-weight: 700; }
    .stAlert { background-color: #1E1E1E; border: 1px solid #333; color: white; }
    .metric-card { background-color: #1A1A1A; border: 1px solid #333; padding: 15px; border-radius: 8px; }
    .console-text { font-family: 'Courier New', monospace; color: #4CC9F0; }
</style>
""", unsafe_allow_html=True)

# ==========================================
# 2. LOAD REAL INTELLIGENCE (THE NEW FEATURE)
# ==========================================
def load_live_intel():
    """Reads the JSON file generated by the Sentinel System."""
    log_file = "live_intelligence_log.json"
    if os.path.exists(log_file):
        try:
            with open(log_file, 'r') as f:
                data = json.load(f)
            return data
        except:
            return []
    return []

live_intel_data = load_live_intel()

# ==========================================
# 3. SIDEBAR CONTROL PANEL
# ==========================================
st.title("📡 Control Panel")

# ADD THIS BUTTON
if st.button("🔄 Force Refresh Intelligence"):
    st.rerun()

st.markdown("---")
# ... rest of your sidebar code ...    

with st.sidebar:
    st.title("📡 Control Panel")
    st.markdown("---")
    
    st.subheader("📍 Target Zone")
    selected_dyad = st.selectbox(
        "Select Conflict to Monitor:",
        ["India-Pakistan", "Russia-Ukraine", "Israel-Palestine"],
        index=0
    )
    
    # Status Indicator
    if live_intel_data:
        latest_risk = live_intel_data[0].get('risk_score', 0)
        if latest_risk > 0.7:
            st.error(f"🔴 LIVE THREAT: CRITICAL ({latest_risk*100:.0f}%)")
        elif latest_risk > 0.4:
            st.warning(f"🟠 LIVE THREAT: ELEVATED ({latest_risk*100:.0f}%)")
        else:
            st.success(f"🟢 LIVE THREAT: STABLE ({latest_risk*100:.0f}%)")
    else:
        st.info("🟡 LIVE FEED: OFFLINE (Using Sim Data)")

    st.markdown("---")
    st.caption("Last System Update: " + datetime.now().strftime("%H:%M:%S"))

# ==========================================
# 4. 🔴 COMMANDER'S LIVE CONSOLE (NEW)
# ==========================================
st.title(f"🛡️ GeoSentinel: {selected_dyad}")

if live_intel_data:
    latest = live_intel_data[0]
    
    # Only show the console if it's the relevant conflict (Mock logic for demo)
    # In production, you'd filter the JSON by conflict name.
    
    with st.expander("🚨 COMMANDER'S CONSOLE (LIVE INTELLIGENCE)", expanded=True):
        c1, c2 = st.columns([2, 1])
        
        with c1:
            st.subheader("📝 LATEST SITREP (AI-GENERATED)")
            st.markdown(f"**SOURCE:** {latest['source']} | **TIME:** {latest['timestamp']}")
            st.info(f"** INTELLIGENCE BRIEF:** {latest['sitrep']}")
            
            st.markdown("### 🎯 STRATEGIC OPTIONS")
            for i, option in enumerate(latest['options']):
                st.write(f"**{i+1}.** {option}")
                
        with c2:
            st.subheader("⚠️ THREAT METER")
            risk_val = latest['risk_score'] * 100
            
            fig_gauge = go.Figure(go.Indicator(
                mode = "gauge+number",
                value = risk_val,
                title = {'text': "HOSTILITY INDEX"},
                gauge = {
                    'axis': {'range': [0, 100]},
                    'bar': {'color': "#EF233C" if risk_val > 70 else "#F4A261"},
                    'bgcolor': "black",
                    'steps': [
                        {'range': [0, 40], 'color': "rgba(0, 255, 0, 0.3)"},
                        {'range': [40, 70], 'color': "rgba(255, 165, 0, 0.3)"},
                        {'range': [70, 100], 'color': "rgba(255, 0, 0, 0.3)"}
                    ]
                }
            ))
            fig_gauge.update_layout(height=250, margin=dict(l=20,r=20,t=0,b=20))
            st.plotly_chart(fig_gauge, use_container_width=True)
            
            st.caption(f"Based on analysis of: '{latest['headline']}'")

else:
    st.warning("⚠️ Live Intelligence Feed is Offline. Run 'sentinel_system.py' to update.")

# ==========================================
# 5. HISTORICAL DATA (EXISTING SIMULATION)
# ==========================================
# This keeps your charts working even if live news is slow
st.markdown("---")
st.subheader("📉 Historical Trend Analysis (Simulation)")

# Load Data
df = data_ingestion.generate_synthetic_data(selected_dyad)
calculator = index_calculator.IndexCalculator()
final_df = calculator.process_index(df)
final_df['date'] = pd.to_datetime(final_df['date'])

# Charts
tab1, tab2 = st.tabs(["Tension Timeline", "Geospatial Map"])

with tab1:
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, row_heights=[0.7, 0.3])
    fig.add_trace(go.Scatter(x=final_df['date'], y=final_df['GPTI'], name='GPTI Score', line=dict(color='#EF233C', width=2), fill='tozeroy'), row=1, col=1)
    fig.add_trace(go.Scatter(x=final_df['date'], y=final_df['weight_kinetic'], name='Kinetic Weight', line=dict(color='#F4A261')), row=2, col=1)
    fig.update_layout(height=500, template="plotly_dark", title="Conflict Evolution Index")
    st.plotly_chart(fig, use_container_width=True)

with tab2:
    st.markdown("### 🗺️ Live Event Tracker")
    map_df, lat, lon, zoom = data_ingestion.generate_location_data(selected_dyad, 500)
    
    st.pydeck_chart(pdk.Deck(
        map_style=None,
        initial_view_state=pdk.ViewState(latitude=lat, longitude=lon, zoom=zoom, pitch=45),
        layers=[
            pdk.Layer(
                'HexagonLayer',
                data=map_df,
                get_position='[lon, lat]',
                radius=4000,
                elevation_scale=50,
                elevation_range=[0, 1000],
                pickable=True,
                extruded=True,
            )
        ]
    ))